cookie:
  expiry_days: 30
  key: clave123
  name: auth_cookie
credentials:
  usernames:
    slenis:
      email: slenis@bancolombia.com
      failed_login_attempts: 0
      first_name: Sergio
      last_name: Lenis
      logged_in: false
      password: $2b$12$HnrJBwIUsxdz6xaleolpcOAOP1KSjwumAVLauPYM7tyVe2aD/BYYq
    wileon:
      email: wileon@bancolombia.com
      first_name: Wilson
      last_name: Leon
      logged_in: false
      password: $2b$12$m2iVyVnqXEMS.8fKDhWFN.ay9aHwcBDwBEjXOIIsta.cvYXVKNDlG
preauthorized:
  emails:
  - slenis@bancolombia.com
  - wileon@bancolombia.com
